# Generated by Django 3.1.7 on 2021-06-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0002_auto_20210613_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sesixon',
            new_name='Sesion',
        ),
    ]
