# Generated by Django 3.1.7 on 2021-06-13 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0004_algoritmotrading'),
    ]

    operations = [
        migrations.AddField(
            model_name='algoritmotrading',
            name='autor',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algoritmotrading',
            name='descripcion',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algoritmotrading',
            name='imagen',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sesion',
            name='algoritmo_elegido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Interface.algoritmotrading'),
        ),
    ]
