# Generated by Django 3.1.7 on 2021-06-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0005_auto_20210613_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algoritmotrading',
            name='descripcion',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
