# Generated by Django 3.1.7 on 2021-06-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0006_auto_20210613_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algoritmotrading',
            name='descripcion',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
