# Generated by Django 3.1.7 on 2021-06-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0008_auto_20210613_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='logued_MT5',
            field=models.BooleanField(default=True),
        ),
    ]
