# Generated by Django 3.1.7 on 2021-08-11 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Interface', '0010_mercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='logued_MT5',
            field=models.BooleanField(default=False),
        ),
    ]
