# Generated by Django 3.1.7 on 2021-09-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0011_auto_20210812_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='raw_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
